name: benjamin
favicon: null
layout_spectrum: 0.85276
typography_spectrum: 0.19902
title: Benjamin Bachman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c1618'
    - '#c4d7db'
    - '#1f4444'
    - '#3b6c69'
    - '#9f6c00'
  brandStrength: 0.25
  lightness: 0.9227062645368278
  saturation: 0.5367907895706594
  rhythmicContrast: 0.0015772851184010506
purpose: []
